version: '3.4'
services:
  traefik:
    image: traefik:2.8
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
    ports:
      - 80:80
      - 443:443
      - 8001:8080
    volumes:
      - ./config:/config