version: '3.4'
services:
  traefik:
    image: traefik:2.8
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.http.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.https.address=:443"
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
      - "--certificatesResolvers.letsEncrypt.acme.email=a@popov.by"
      - "--certificatesResolvers.letsEncrypt.acme.storage=/data/acme.json"
      - "--certificatesResolvers.letsEncrypt.acme.tlschallenge=true"
      - "--certificatesResolvers.letsEncrypt.acme.httpChallenge.entryPoint=http"
    ports:
      - "25:25"
      - "80:80"
      - "443:443"
      - "465:465"
      - "993:993"
      - "995:995"
      - "4190:4190"
      - "8001:8080"
    volumes:
      - ./config:/config
      - ./data:/data